Name:           ros-indigo-cost-map-ros
Version:        0.3.3
Release:        0%{?dist}
Summary:        ROS cost_map_ros package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       opencv-devel
Requires:       ros-indigo-cost-map-core
Requires:       ros-indigo-cost-map-msgs
Requires:       ros-indigo-costmap-2d
Requires:       ros-indigo-ecl-build
Requires:       ros-indigo-ecl-command-line
Requires:       ros-indigo-ecl-console
Requires:       ros-indigo-grid-map-core
Requires:       ros-indigo-grid-map-costmap-2d
Requires:       ros-indigo-grid-map-ros
Requires:       ros-indigo-grid-map-visualization
Requires:       ros-indigo-nav-msgs
Requires:       ros-indigo-roslib
Requires:       yaml-cpp-devel
BuildRequires:  boost-devel
BuildRequires:  opencv-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-cost-map-core
BuildRequires:  ros-indigo-cost-map-msgs
BuildRequires:  ros-indigo-costmap-2d
BuildRequires:  ros-indigo-ecl-build
BuildRequires:  ros-indigo-ecl-command-line
BuildRequires:  ros-indigo-ecl-console
BuildRequires:  ros-indigo-grid-map-core
BuildRequires:  ros-indigo-grid-map-costmap-2d
BuildRequires:  ros-indigo-grid-map-ros
BuildRequires:  ros-indigo-grid-map-visualization
BuildRequires:  ros-indigo-nav-msgs
BuildRequires:  ros-indigo-roslib
BuildRequires:  yaml-cpp-devel

%description
Cost maps, following the style of ethz-asl's grid_map library.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Jan 01 2018 Daniel Stonier <d.stonier@gmail.com> - 0.3.3-0
- Autogenerated by Bloom

* Mon Aug 07 2017 Daniel Stonier <d.stonier@gmail.com> - 0.3.2-0
- Autogenerated by Bloom

* Thu Feb 16 2017 Daniel Stonier <d.stonier@gmail.com> - 0.3.1-0
- Autogenerated by Bloom

* Tue Dec 27 2016 Daniel Stonier <d.stonier@gmail.com> - 0.3.0-0
- Autogenerated by Bloom

